mashgame/urls.py
from django.urls import path

from . import views

app_name = "mashgame"
urlpatterns = [
    path("", views.mashgame, name="mashgame"),
    path("login/", views.login, name="login"),
    path("signup/", views.signup, name="signup"),
    path("ajax/validate_username", views.validate_username, name="validate_username"),
    path("joinLoginUser/", views.joinLoginUser, name="join_login_user"),
    path("joinSignupUser/", views.joinSignupUser, name="join_signup_user"),
    path("<str:user_name>/", views.userProfile, name="user_profile"),
    path("<str:user_name>/preference/", views.userPreference, name="user_preference"),
    path("<str:user_name>/logout/", views.userLogout, name="user_logout"),
    path("<str:user_name>/savePreference/", views.savePreference, name="save_preference"),
    path("<str:user_name>/sent_attacks/", views.sentAttacks, name="sent_attacks"),
    path("<str:user_name>/show_users/", views.showUsers, name="show_users"),
    path("<str:user_name>/sent_attack_details/<int:attack_id>/", views.sentAttackDetails, name="sent_attack_details"),
    path("<str:user_name>/send_attack/<str:reciever_name>", views.sendAttack, name="send_attack"),
    path("<str:user_name>/save_attack/<str:reciever_name>", views.saveAttack, name="save_attack"),
    path("<str:user_name>/rank_list/", views.rankList, name="rank_list")
]

mashzen/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('mashgame/', include('mashgame.urls')),
    path('admin/', admin.site.urls),
]

mashgame/models/attack.py
from django.db import models
from .data import MASHData
from .user import User

class AttackManager(models.Manager):
    def assignByDefault(self, attacker, reciever):
        attack_data = MASHData.objects.getDefault()
        attack = Attack(attacker=attacker, reciever=reciever, attack_data=attack_data)
        attack.result_data = None 
        attack.save()
        return attack


class Attack(models.Model):
    objects = AttackManager()
    attacker = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sent_attacks")
    reciever = models.ForeignKey(User, on_delete=models.CASCADE, related_name="recieved_attacks")
    attack_data = models.OneToOneField(MASHData, on_delete=models.CASCADE, related_name="attack_data", null=True, default=None)


    def __str__(self):
        return self.attacker.user_name+" --> "+self.reciever.user_name

mashgame/models/preference.py
from django.db import models
from .data import MASHData
from .user import User

class PreferenceManager(models.Manager):
    def assignByDefault(self, user):
        print("==> Assigning a default preference for the user: ", user.user_name)
        mash_data = MASHData.objects.getDefault()
        preference = Preference(user=user, mash_data=mash_data)
        preference.save()
        print("==> Preference saved.")
        return preference

class Preference(models.Model):
    objects = PreferenceManager()
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mash_data = models.OneToOneField(MASHData, on_delete=models.CASCADE)

    def __str__(self):
        data = [self.mash_data.home_1.value, self.mash_data.spouse_1.value, self.mash_data.numchild_1.value,
                self.mash_data.luxury_1.value]
        return ("|".join(data))

mashgame/models/result.py
from django.db import models
from .attack import Attack
from .data import *

class ResultDataManager(models.Manager):
    def getDefault(self, attack=None):
        result = ResultData(attack=attack)
        result.save()
        return result


class ResultData(models.Model):
    objects = ResultDataManager()
    home = models.ForeignKey(Home, on_delete=models.SET_NULL, null=True, related_name="+")
    spouse = models.ForeignKey(Spouse, on_delete=models.SET_NULL, null=True, related_name="+")
    numchild = models.ForeignKey(NumChild, on_delete=models.SET_NULL, null=True, related_name="+")
    luxury = models.ForeignKey(Luxury, on_delete=models.SET_NULL, null=True, related_name="+")
    mash_value = models.IntegerField(default=0)
    available = models.BooleanField(default=False)
    attacker_points = models.IntegerField(default=0)
    reciever_points = models.IntegerField(default=0)
    attack = models.OneToOneField(Attack, on_delete=models.CASCADE, related_name="result_data", null=True, default=None)
    
    def __str__(self):
        return f"avalable: {self.available}"

mashgame/views.py
from django.shortcuts import render
from django.shortcuts import redirect

# Create your views here.
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.urls import reverse
from .models import User
from .models import Preference
from .models import Home, Spouse, NumChild, Luxury

def mashgame(request):
    request.session["error_message"] = None
    return render(request, "mashgame/mashgame.html", {"error_message": request.session.get("error_message")})



def getAuthenticatedUser(request, user_name):
    # at the top check if any user session is exist
    if not request.session.get("user_name") or not request.session.get("user_hash"):
        return None

    # if there's user_name in session data, check if it match with the requested user_name
    # else return None
    if request.session["user_name"] != user_name:
        user_name = request.session["user_name"]

    # get filtered QuerySet
    query_set = User.objects.filter(user_name__iexact=user_name)
    # return None if a user with user_name doesn't exist
    if not query_set.exists():
        # delete user_name and user_hash form the session data for future clarification
        request.session["user_name"] = None
        request.session["user_hash"] = None
        return None
    # get the user with user_name
    user = query_set.first()

    # check registered session hash with current session hash
    if request.session.get("user_hash") in user.hashValues():
        return user
    # else means invalid session data
    request.session["user_name"] = None
    request.session["user_hash"] = None
    return None


def login(request):
    # First check if already a session exists
    user = getAuthenticatedUser(request, None)
    if user:
        return redirect("mashgame:user_profile", user_name=user.user_name)
    return render(request, "mashgame/login.html", {"error_message": request.session.get("error_message")})

def signup(request):
    # First check if already a session exists
    user = getAuthenticatedUser(request, None)
    if user:
        return redirect("mashgame:user_profile", user_name=user.user_name)

    return render(request, "mashgame/signup.html", {"error_message": request.session.get("error_message")})


def validate_username(request):
    user_name = request.GET.get("user_name", None)
    data = {
        "is_taken": User.objects.filter(user_name__iexact=user_name).exists()
    }
    return JsonResponse(data)


def joinSignupUser(request):
    user_name = request.POST["user_name"]
    password = request.POST["password"]

    if User.objects.filter(user_name__iexact=user_name).exists():
            request.session["error_message"] = f"Username already exists: {user_name}"
            return redirect("mashgame:signup")

    user_signup_res = User.objects.signup(user_name=user_name, password=password)
    if not user_signup_res:
        request.session["error_message"] = f"Failed on registering the user: {user_name}"
        return redirect("mashgame:signup")

    user = user_signup_res["user"]
    user_hash = user_signup_res["user_hash"]

    if not user_hash:
        request.session["errror_message"] = f"Failed on authorizing the user: {user_name}"
        return redirect("mashgame:login")

    # keep user_name and user_hash in session data
    request.session["user_name"] = user.user_name
    request.session["user_hash"] = user_hash
    request.session["error_message"] = None

    return redirect("mashgame:user_profile", user_name=user.user_name)


def joinLoginUser(request):
    user_name = request.POST["user_name"]
    password = request.POST["password"]

    if not User.objects.filter(user_name__iexact=user_name).exists():
        request.session["error_message"] = "Username doesn't exist!"
        return redirect("mashgame:mashgame")

    #  User.objects.get_authorized_user(user_name, password) will return a dict on success
    authorized_dict = User.objects.get_authorized_user(user_name, password)
    user = authorized_dict.get("user")
    user_hash = authorized_dict.get("user_hash")

    if not user or not user_hash:
        request.session["error_message"] = "Failed on authorizing the user!"
        return redirect("mashgame:mashgame")

    # keep user_name and user_hash in session data
    request.session["user_name"] = user.user_name
    request.session["user_hash"] = user_hash
    request.session["error_message"] = None

    if request.session.get("page_requested"):
        return redirect(request.session.get("page_requested"), user_name=user.user_name)

    return redirect("mashgame:user_profile", user_name=user.user_name)


def userProfile(request, user_name):
    request.session["page_requested"] = "mashgame:user_profile"
    user = getAuthenticatedUser(request, user_name)
    if not user:
        return redirect("mashgame:login")

    return render(request, "mashgame/user_profile.html", {"user": user})


def userPreference(request, user_name):
    request.session["page_requested"] = "mashgame:user_preference"
    user = getAuthenticatedUser(request, user_name)
    if not user:
        return redirect("mashgame:login")

    class Pref:
        def __init__(self, type_name, type_header, opts, so1i, so2i):
            self.type_name = type_name
            self.type_header = type_header
            self.opts = opts
            self.soptid_1 = so1i
            self.soptid_2 = so2i

    try:
        mash_data = user.preference.mash_data
    except User.preference.RelatedObjectDoesNotExist:
        Preference.objects.createAPreferenceWithDefaultMASHData(user=user)
        mash_data = user.preference.mash_data

    home_pref = Pref("home", "Home", list(Home.objects.all()),
                        mash_data.home_1.id,
                        mash_data.home_2.id)

    spouse_pref = Pref("spouse", "Spouse", list(Spouse.objects.all()),
                        mash_data.spouse_1.id,
                        mash_data.spouse_2.id)

    numchild_pref = Pref("numchild", "Number of Child", list(NumChild.objects.all()),
                        mash_data.numchild_1.id,
                        mash_data.numchild_2.id)

    luxury_pref = Pref("luxury", "Luxury", list(Luxury.objects.all()),
                        mash_data.luxury_1.id,
                        mash_data.luxury_2.id)


    prefs = [home_pref, spouse_pref, numchild_pref, luxury_pref]
    return render(request, "mashgame/user_preference.html", {"user": user, "prefs": prefs})


def savePreference(request, user_name):
    request.session["page_requested"] = "mashgame:user_preference"

    user = getAuthenticatedUser(request, user_name)
    if not user:
        return redirect("mashgame:login")

    home_1_id = int(request.POST["selected_home_1"])
    home_2_id = int(request.POST["selected_home_2"])
    spouse_1_id = int(request.POST["selected_spouse_1"])
    spouse_2_id = int(request.POST["selected_spouse_2"])
    numchild_1_id = int(request.POST["selected_numchild_1"])
    numchild_2_id = int(request.POST["selected_numchild_2"])
    luxury_1_id = int(request.POST["selected_luxury_1"])
    luxury_2_id = int(request.POST["selected_luxury_2"])
    lucky_number = int(request.POST["lucky_number"])

    mash_data = user.preference.mash_data
    mash_data.home_1 = Home.objects.get(id=home_1_id)
    mash_data.home_2 = Home.objects.get(id=home_2_id)
    mash_data.spouse_1 = Spouse.objects.get(id=spouse_1_id)
    mash_data.spouse_2 = Spouse.objects.get(id=spouse_2_id)
    mash_data.numchild_1 = NumChild.objects.get(id=numchild_1_id)
    mash_data.numchild_2 = NumChild.objects.get(id=numchild_2_id)
    mash_data.luxury_1 = Luxury.objects.get(id=luxury_1_id)
    mash_data.luxury_2 = Luxury.objects.get(id=luxury_2_id)
    mash_data.save()
    user.lucky_number = lucky_number
    user.save()

    return redirect("mashgame:user_profile", user_name=user_name)

def userLogout(request, user_name):
    request.session["page_requested"] = None
    user = getAuthenticatedUser(request, user_name)
    if not user:
        return redirect("mashgame:login")


    user.deauthorizeHash(request.session.get("user_hash"))
    # delete user authentication session data
    request.session["user_hash"] = None
    request.session["user_name"] = None
    request.session["page_requested"] = None
    return redirect("mashgame:login")

def showUsers(request, user_name):
    pass 

mashgame/views/authentication.py
from django.shortcuts import render
from django.shortcuts import redirect

from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.urls import reverse
from mashgame.models import User



def getAuthenticatedUser(request, user_name):
    # at the top check if any user session is exist
    if not request.session.get("user_name") or not request.session.get("user_hash"):
        return None

    # if there's user_name in session data, check if it match with the requested user_name
    # else return None
    if request.session["user_name"] != user_name:
        user_name = request.session["user_name"]

    # get filtered QuerySet
    query_set = User.objects.filter(user_name__iexact=user_name)
    # return None if a user with user_name doesn't exist
    if not query_set.exists():
        # delete user_name and user_hash form the session data for future clarification
        request.session["user_name"] = None
        request.session["user_hash"] = None
        return None
    # get the user with user_name
    user = query_set.first()

    # check registered session hash with current session hash
    if request.session.get("user_hash") in user.hashValues():
        return user
    # else means invalid session data
    request.session["user_name"] = None
    request.session["user_hash"] = None
    return None


def login(request):
    # First check if already a session exists
    user = getAuthenticatedUser(request, None)
    if user:
        return redirect("mashgame:user_profile", user_name=user.user_name)
    return render(request, "mashgame/login.html", {"error_message": request.session.get("error_message")})

def signup(request):
    # First check if already a session exists
    user = getAuthenticatedUser(request, None)
    if user:
        return redirect("mashgame:user_profile", user_name=user.user_name)

    return render(request, "mashgame/signup.html", {"error_message": request.session.get("error_message")})


def validate_username(request):
    user_name = request.GET.get("user_name", None)
    data = {
        "is_taken": User.objects.filter(user_name__iexact=user_name).exists()
    }
    return JsonResponse(data)


def joinSignupUser(request):
    user_name = request.POST["user_name"]
    password = request.POST["password"]

    if User.objects.filter(user_name__iexact=user_name).exists():
            request.session["error_message"] = f"Username already exists: {user_name}"
            return redirect("mashgame:signup")

    user_signup_res = User.objects.signup(user_name=user_name, password=password)
    if not user_signup_res:
        request.session["error_message"] = f"Failed on registering the user: {user_name}"
        return redirect("mashgame:signup")

    user = user_signup_res["user"]
    user_hash = user_signup_res["user_hash"]

    if not user_hash:
        request.session["errror_message"] = f"Failed on authorizing the user: {user_name}"
        return redirect("mashgame:login")

    # keep user_name and user_hash in session data
    request.session["user_name"] = user.user_name
    request.session["user_hash"] = user_hash
    request.session["error_message"] = None

    return redirect("mashgame:user_profile", user_name=user.user_name)


def joinLoginUser(request):
    request.session["error_message"] = None
    user_name = request.POST["user_name"]
    password = request.POST["password"]

    if not User.objects.filter(user_name__iexact=user_name).exists():
        request.session["error_message"] = "Username doesn't exist!"
        return redirect("mashgame:login")

    #  User.objects.get_authorized_user(user_name, password) will return a dict on success
    authorized_dict = User.objects.login(user_name, password)
    if not authorized_dict:
        request.session["error_message"] = f"Failed on authorising the user: {user_name}"
        return redirect("mashgame:login")

    user = authorized_dict.get("user")
    user_hash = authorized_dict.get("user_hash")

    if not user or not user_hash:
        request.session["error_message"] = "Failed on authorizing the user!"
        return redirect("mashgame:mashgame")

    # keep user_name and user_hash in session data
    request.session["user_name"] = user.user_name
    request.session["user_hash"] = user_hash
    request.session["error_message"] = None

    if request.session.get("page_requested"):
        return redirect(request.session.get("page_requested"), user_name=user.user_name)

    return redirect("mashgame:user_profile", user_name=user.user_name)

mashgame/views/common_views.py
from django.shortcuts import render
from django.shortcuts import redirect

# Create your views here.
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.urls import reverse
from mashgame.models import User
from mashgame.models import Preference
from mashgame.models import Home, Spouse, NumChild, Luxury
from .authentication import getAuthenticatedUser

def attackDetails(request, pk):
    pass

mashgame/templates/mashgame/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mashzen | Mashgame</title>
    <script src="{% static 'mashgame/jquery.js' %}"></script>
    <link rel="stylesheet" type="text/css" href={% static 'mashgame/base.css' %}>
    <style>
      a{
        text-decoration: none;
      }
      .center{
        margin-left: auto;
        margin-right: auto;
      }
      table, th {
        padding: 5px;
        border: 1px solid black;
        border-collapse: collapse;
      }
      td {
        padding: 5px 5px 5px 20px;
        border: 1px solid black;
        border-collapse: collapse;
      }
      fieldset {
        margin-left: auto;
        margin-right: auto;
        background-color: #eeeeee;
      }

      legend {
        background-color: gray;
        color: white;
        padding: 5px 10px;
      }
      li{
        text-align: center;
      }
    </style>
  </head>

  <div style="text-align: center">
    <a href="{% url 'mashgame:mashgame' %}" style="text-decoration: none"><h1>Mashgame</h1></a>
  <div>
  {% block body %}
  {% endblock %}
</html>

mashgame/templates/mashgame/login.html
{% include 'mashgame/base.html' %}
<html>
  {% block body %}
  <body>
    <div style="text-align: center">
      <h3>Login</h3>
    <div>

    <div style="text-align: center">
      <form action="{% url 'mashgame:join_login_user' %}" name="user_login_form" method="post">
        {% csrf_token %}
        {% if error_message %}
          <label style="color: red"><b>{{error_message}}</b></label>
          <br>
        {% endif %}
        <label for="user_name"><b>Username</b></label>
        <br>
        <input type="text" placeholder="user name" name="user_name" id="js_user_name" autocomplete="off" autofocus required>
        <br>
        <br>
        <label for="password" id="js_password_label"><b>Password</b></label>
        <br>
        <input type="password" placeholder="password" name="password" id="js_password" minlength="4" maxlength="10" required >
        <br>
        <br>
        <button type="submit" id="js_login_button">Login</button>
      </form>
      <br>
      <a href="{% url 'mashgame:signup' %}">Create a new user</a>
    </div>
    <div align="center">
      <label id="js_reload"></label>
    </div>
    {% block javascript %}
      <script>
        $("#js_user_name").keyup(function(){
          var user_name = $(this).val();

          $.ajax({
            url: "{% url 'mashgame:validate_username' %}",
            data: {
              'user_name': user_name
            },
            dataType: 'json',
            success: function(res_data) {
              if( !res_data.is_taken) {
                document.getElementById("js_user_name").style.borderColor = "read";
                $("#js_password").hide();
                $("#js_login_button").hide();
                $("#js_password_label").hide();

              }
              else{
                document.getElementById("js_user_name").style.borderColor = "green";
                $("#js_password_label").show();
                $("#js_password").show();
                $("#js_login_button").show();
              }
            }
          });
        });
      </script>
    {% endblock %}
  </body>
  {% endblock %}
</html>

mashgame/templates/mashgame/send_attack.html
{% include 'mashgame/base.html' %}
{% include 'mashgame/user_profile_base.html' %}

<div style="text-align: center">
  <h4>Send To: {{reciever.user_name}}</h4>
  <form name="attack_data" action="{% url 'mashgame:save_attack' user.user_name reciever.user_name %}" method="post" autocomplete="off">
    {% csrf_token %}

    {% for pref in prefs %}
      <label for="{{pref.type_name}}_choices" id="js_{{pref.type_name}}_choices_label"><h4>{{pref.type_header}} Choices</h4></label>
      <select name="selected_{{pref.type_name}}_1" id="js_{{pref.type_name}}_1_select" onmousedown="setConSize(this, 4);" onblur="setSize(this, 0);" onchange="setSize(this, 0);">

        {% for opt in pref.opts %}
          {% if pref.soptid_1 == opt.id %}
            <option value="{{opt.id}}" selected>{{opt.value}}</option>
          {% else %}
            <option value="{{opt.id}}">{{opt.value}}</option>
          {% endif %}
        {% endfor %}
      </select>
      <br>or<br>
      <select name="selected_{{pref.type_name}}_2" id="js_{{pref.type_name}}_2_select" onmousedown="setConSize(this, 4);" onblur="setSize(this, 0);" onchange="setSize(this, 0);">
        {% for opt in pref.opts %}
          {% if pref.soptid_2 == opt.id %}
            <option value="{{opt.id}}" selected>{{opt.value}}</option>
          {% else %}
            <option value="{{opt.id}}" >{{opt.value}}</option>
          {% endif %}
        {% endfor %}
      </select>
      <br>
      <br>
      <br>
    {% endfor %}
    {% if reciever.attack_status == "attack" %}
      <button type="submit" name="submit_type" value="send">Send</button>
    {% else %}
      <button type="submit" name="submit_type" value="save">Save</button>
    {% endif %}
  </form>
</div>

{% block script %}
<script>
  function setConSize(object, value){
    if(object.options.length>value)
      object.size=value;
  }

  function setSize(object, value){
    object.size = value;
  }
</script>
{% endblock %}

mashgame/templates/mashgame/sent_attack_details.html
{% load mashgame_extras %}
{% include 'mashgame/base.html' %}
{% include 'mashgame/user_profile_base.html' %}


<br>
<div style="text-align: center">
  <h3>Attack Details</h3>
</div>

<div style="text-align: align">

  <table class="center">
    <caption><h5>To: {{attack.reciever.user_name}}</h5></caption>
    <tr>
      <th><h6>Homes</h6></th>
      <td>
        <ol>
          <li>{{attack.attack_data.home_1.value}}</li>
          <li>{{attack.attack_data.home_2.value}}</li>
        </ol>
      </td>
    </tr>

    <tr>
      <th><h6>Spouses</h6></th>
      <td>
        <ol>
          <li>{{attack.attack_data.spouse_1.value}}</li>
          <li>{{attack.attack_data.spouse_2.value}}</li>
        </ol>
      </td>
    </tr>

    <tr>
      <th><h6>Number of Childs</h6></th>
      <td>
        <ol>
          <li>{{attack.attack_data.numchild_1.value}}</li>
          <li>{{attack.attack_data.numchild_2.value}}</li>
        </ol>
      </td>
    </tr>

    <tr>
      <th><h6>Luxury Items</h6></th>
      <td>
        <ol>
          <li>{{attack.attack_data.luxury_1.value}}</li>
          <li>{{attack.attack_data.luxury_2.value}}</li>
        </ol>
      </td>
    </tr>
  </table>
  <br>
  <a href="{% url 'mashgame:send_attack' user.user_name attack.reciever.user_name %}">Edit</a>
  <br>
  <a href="{% url 'mashgame:show_users' user.user_name %}">Send Attacks</a>
  <br>
</div>

mashgame/templates/mashgame/sent_attacks.html
{% load mashgame_extras %}
{% include 'mashgame/base.html' %}
{% include 'mashgame/user_profile_base.html' %}


<br>
<div style="text-align: center">
  <h3>Sent Attacks</h3>
</div>

<div style="text-align: center">
  {% for index, sent_attack in sent_attacks|enum %}
    <table class="center">
      <caption><h5>To: {{index}}. {{sent_attack.reciever.user_name}}</h5></caption>
      <tr>
        <th>Home Choice 1</th>
        <td>{{sent_attack.attack_data.home_1.value}}</td>
      </tr>

      <tr>
        <th>Spouse Choice 1</th>
        <td>{{sent_attack.attack_data.spouse_1.value}}</td>
      </tr>
      <tr>
        <th>Number of Childs Choice 1</th>
        <td>{{sent_attack.attack_data.numchild_1.value}}</td>
      </tr>
      <tr>
        <th>Luxury Choice 1</th>
        <td>{{sent_attack.attack_data.luxury_1.value}}</td>
      </tr>
    </table>
    <a href="{% url 'mashgame:sent_attack_details' user.user_name sent_attack.id %}">Show</a>
    <br>
    <br>
  {% endfor %}
</div>

mashgame/templates/mashgame/signup.html
{% include 'mashgame/base.html' %}
<html>
{% block body %}
  <body>
    <div style="text-align: center">
      <h3>Signup</h3>
    <div>
    <div style="text-align: center">
      <form action="{% url 'mashgame:join_signup_user' %}" name="user_signup_form" method="post" autocomplete="off">
        {% csrf_token %}
        <label for="user_name"><b>Username</b></label>
        <br>
        <input type="text" placeholder="user name" name="user_name" id="js_user_name" autofocus required>
        <label id="js_user_name_exist_label"></label>
        <br>
        <br>
        <label for="password" id="js_password_label"><b>Password</b></label>
        <br>
        <input type="password" placeholder="password" name="password" id="js_password" minlength="4" maxlength="10" required >
        <br>
        <br>
        <label for="confirm_password" id="js_confirm_password_label"><b>Confirm Password</b></label>
        <br>
        <input type="password" placeholder="confirm password" name="confirm_password" id="js_confirm_password" minlength="4" maxlength="10" onkeyup="check()" required >
        <br>
        <br>
        <button type="submit" id="js_signup_button">Signup</button>
      </form>
      <br>
      <a href="{% url 'mashgame:login' %}">Login</a>
    </div>


    {% block javascript %}
      <script>
        $("#js_user_name").focus();
        $("#js_user_name").keyup(function(){
          var user_name = $(this).val();

          $.ajax({
            url: "{% url 'mashgame:validate_username' %}",
            data: {
              'user_name': user_name
            },
            dataType: 'json',
            success: function(res_data) {
              if(res_data.is_taken) {
                document.getElementById("js_user_name").style.borderColor = "red";
                $("#js_password_label").hide();
                $("#js_password").hide();
                $("#js_confirm_password_label").hide();
                $("#js_confirm_password").hide();
                $("#js_signup_button").hide();

              }
              else{
                document.getElementById("js_user_name").style.borderColor = "green";
                $("#js_pass")
                $("#js_password").show();
                $("#js_confirm_password").show();
                $("#js_signup_button").show();
              }
            }
          });
        });

        var check = function(){
          if(document.getElementById('js_password').value==
             document.getElementById('js_confirm_password').value){
            document.getElementById("js_confirm_password").style.borderColor = "green";
            $("#js_signup_button").show();
          }
          else {
            document.getElementById("js_confirm_password").style.borderColor = "red";
            $("#js_signup_button").hide();
          }
        }
      </script>
    {% endblock %}
  </body>
{% endblock %}
</html>

mashgame/templates/mashgame/user_profile.html
{% include 'mashgame/base.html' %}
{% include 'mashgame/user_profile_base.html' %}

<h4>Gender: {{user.gender}}</h4>
<h4>Lucky Number: {{user.lucky_number}}</h4>
<h4>You have recieved {{user.recievedAttacks|length}} attacks</h4>
<a href="{% url 'mashgame:user_preference' user.user_name %}">preference</a>
<br>
<a href="{% url 'mashgame:sent_attacks' user.user_name %}">sent attacks</a>
<br>
<a href="{% url 'mashgame:show_users' user.user_name %}">send attacks</a>
<br>
<a href="{% url 'mashgame:rank_list' user.user_name %}">rank list</a>
<br>
<a href="{% url 'mashgame:user_logout' user.user_name %}">logout</a>

mashgame/templates/mashgame/user_profile_base.html
<br>
<a href="{% url 'mashgame:user_profile' user.user_name %}">
  <h3>User Name: {{ user.user_name }}</h3>
</a>

mashgame/templates/mashgame/users_table.html
{% load mashgame_extras %}
{% include 'mashgame/base.html' %}
{% include 'mashgame/user_profile_base.html' %}

<style>
  .center{
    margin-left: auto;
    margin-right: auto;
  }
  table, th, td {
    padding: 10px;
    border: 1px solid black;
    border-collapse: collapse;
  }
</style>

<table class="center">
  <caption><h5>Users</h5></caption>
  <tr>
    <th>Index</th>
    <th>User Name</th>
    <th>Gender</th>
    <th>Attack Status</th>
  </tr>
  {% for index, a_user in available_users|enum %}
    <tr>
      <td>{{index}}</td>
      <td>{{a_user.user_name}}</td>
      <td>{{a_user.gender}}</td>
      <td>
        <a href="{% url 'mashgame:send_attack' user.user_name a_user.user_name %}">{{a_user.attack_status}}</a>
      </td>
    </tr>
  {% endfor %}
</table>
<br>
<br>